// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Safety setting, affecting the safety-blocking behavior. Passing a safety setting for a category changes the allowed proability that content is blocked.
public struct SafetySetting: Codable {
  /// Required. The category for this setting.
  public var category: Category?
  /// Required. Controls the probability threshold at which harm is blocked.
  public var threshold: Threshold?

  /// Required. The category for this setting.
  public enum Category: String, Codable, CaseIterable {
    case harmCategoryUnspecified = "HARM_CATEGORY_UNSPECIFIED"
    case harmCategoryDerogatory = "HARM_CATEGORY_DEROGATORY"
    case harmCategoryToxicity = "HARM_CATEGORY_TOXICITY"
    case harmCategoryViolence = "HARM_CATEGORY_VIOLENCE"
    case harmCategorySexual = "HARM_CATEGORY_SEXUAL"
    case harmCategoryMedical = "HARM_CATEGORY_MEDICAL"
    case harmCategoryDangerous = "HARM_CATEGORY_DANGEROUS"
  }

  /// Required. Controls the probability threshold at which harm is blocked.
  public enum Threshold: String, Codable, CaseIterable {
    case harmBlockThresholdUnspecified = "HARM_BLOCK_THRESHOLD_UNSPECIFIED"
    case blockLowAndAbove = "BLOCK_LOW_AND_ABOVE"
    case blockMediumAndAbove = "BLOCK_MEDIUM_AND_ABOVE"
    case blockOnlyHigh = "BLOCK_ONLY_HIGH"
    case blockNone = "BLOCK_NONE"
  }

  public init(category: Category? = nil, threshold: Threshold? = nil) {
    self.category = category
    self.threshold = threshold
  }

  public init(from decoder: Decoder) throws {
    let values = try decoder.container(keyedBy: StringCodingKey.self)
    self.category = try values.decodeIfPresent(Category.self, forKey: "category")
    self.threshold = try values.decodeIfPresent(Threshold.self, forKey: "threshold")
  }

  public func encode(to encoder: Encoder) throws {
    var values = encoder.container(keyedBy: StringCodingKey.self)
    try values.encodeIfPresent(category, forKey: "category")
    try values.encodeIfPresent(threshold, forKey: "threshold")
  }
}
