// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Output text returned from a model.
public struct TextCompletion: Codable {
  /// A collection of source attributions for a piece of content.
  public var citationMetadata: CitationMetadata?
  /// Output only. The generated text returned from the model.
  public var output: String?
  /// Ratings for the safety of a response. There is at most one rating per category.
  public var safetyRatings: [SafetyRating]?

  public init(citationMetadata: CitationMetadata? = nil, output: String? = nil, safetyRatings: [SafetyRating]? = nil) {
    self.citationMetadata = citationMetadata
    self.output = output
    self.safetyRatings = safetyRatings
  }

  public init(from decoder: Decoder) throws {
    let values = try decoder.container(keyedBy: StringCodingKey.self)
    self.citationMetadata = try values.decodeIfPresent(CitationMetadata.self, forKey: "citationMetadata")
    self.output = try values.decodeIfPresent(String.self, forKey: "output")
    self.safetyRatings = try values.decodeIfPresent([SafetyRating].self, forKey: "safetyRatings")
  }

  public func encode(to encoder: Encoder) throws {
    var values = encoder.container(keyedBy: StringCodingKey.self)
    try values.encodeIfPresent(citationMetadata, forKey: "citationMetadata")
    try values.encodeIfPresent(output, forKey: "output")
    try values.encodeIfPresent(safetyRatings, forKey: "safetyRatings")
  }
}
