// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// A single example for tuning.
public struct TuningExample: Codable {
  /// Optional. Text model input.
  public var textInput: String?
  /// Required. The expected model output.
  public var output: String?

  public init(textInput: String? = nil, output: String? = nil) {
    self.textInput = textInput
    self.output = output
  }

  public init(from decoder: Decoder) throws {
    let values = try decoder.container(keyedBy: StringCodingKey.self)
    self.textInput = try values.decodeIfPresent(String.self, forKey: "textInput")
    self.output = try values.decodeIfPresent(String.self, forKey: "output")
  }

  public func encode(to encoder: Encoder) throws {
    var values = encoder.container(keyedBy: StringCodingKey.self)
    try values.encodeIfPresent(textInput, forKey: "textInput")
    try values.encodeIfPresent(output, forKey: "output")
  }
}
