// Generated by Create API
// https://github.com/CreateAPI/CreateAPI
//
// Copyright 2023 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// A set of tuning examples. Can be training or validatation data.
public struct TuningExamples: Codable {
  /// Required. The examples. Example input can be for text or discuss, but all examples in a set must be of the same type.
  public var examples: [TuningExample]?

  public init(examples: [TuningExample]? = nil) {
    self.examples = examples
  }

  public init(from decoder: Decoder) throws {
    let values = try decoder.container(keyedBy: StringCodingKey.self)
    self.examples = try values.decodeIfPresent([TuningExample].self, forKey: "examples")
  }

  public func encode(to encoder: Encoder) throws {
    var values = encoder.container(keyedBy: StringCodingKey.self)
    try values.encodeIfPresent(examples, forKey: "examples")
  }
}
