// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
  name: "Google AI Playground",
  platforms: [
    .iOS("16.0"),
  ],
  products: [
    .iOSApplication(
      name: "Google AI Playground",
      targets: ["AppModule"],
      displayVersion: "1.0",
      bundleVersion: "1",
      appIcon: .placeholder(icon: .pencil),
      accentColor: .presetColor(.blue),
      supportedDeviceFamilies: [
        .pad,
        .phone,
      ],
      supportedInterfaceOrientations: [
        .portrait,
        .landscapeRight,
        .landscapeLeft,
        .portraitUpsideDown(.when(deviceFamilies: [.pad])),
      ],
      capabilities: [
        .outgoingNetworkConnections(),
      ]
    ),
  ],
  dependencies: [
    .package(url: "https://github.com/google/generative-ai-swift.git", "0.4.3" ..< "0.5.0"),
  ],
  targets: [
    .executableTarget(
      name: "AppModule",
      dependencies: [
        .product(name: "GoogleGenerativeAI", package: "generative-ai-swift"),
      ],
      path: ".",
      swiftSettings: [
        .enableUpcomingFeature("BareSlashRegexLiterals"),
      ]
    ),
  ]
)
